name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install tooling (Makefile path)
        if: ${{ hashFiles('Makefile') != '' }}
        run: |
          make init

      - name: Install tooling (fallback if no Makefile)
        if: ${{ hashFiles('Makefile') == '' }}
        run: |
          python -m pip install -U pip
          pip install black ruff mypy pytest

      - name: Run quality checks (Makefile path)
        if: ${{ hashFiles('Makefile') != '' }}
        run: |
          make all

      - name: Run quality checks (fallback if no Makefile)
        if: ${{ hashFiles('Makefile') == '' }}
        run: |
          black --check .
          ruff check .
          mypy .
          pytest -q