name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install tooling (justfile path)
        if: ${{ hashFiles('justfile') != '' }}
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies (justfile path)
        if: ${{ hashFiles('justfile') != '' }}
        run: |
          uv sync --extra dev

      - name: Run quality checks (justfile path)
        if: ${{ hashFiles('justfile') != '' }}
        run: |
          ~/.local/bin/just all

      - name: Install tooling (fallback if no justfile)
        if: ${{ hashFiles('justfile') == '' }}
        run: |
          python -m pip install -U pip
          pip install -e ".[dev]"

      - name: Run quality checks (fallback if no justfile)
        if: ${{ hashFiles('justfile') == '' }}
        run: |
          black --check .
          ruff check .
          mypy .
          pytest -q